package cn.com.user.mapper;

import cn.com.user.pojo.TExaAnswerInfo;
import cn.com.user.pojo.TExaAnswerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TExaAnswerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TExaAnswerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TExaAnswerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByPrimaryKey(String answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TExaAnswerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TExaAnswerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TExaAnswerInfo> selectByExample(TExaAnswerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    TExaAnswerInfo selectByPrimaryKey(String answerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TExaAnswerInfo record, @Param("example") TExaAnswerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TExaAnswerInfo record, @Param("example") TExaAnswerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKeySelective(TExaAnswerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_ANSWER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKey(TExaAnswerInfo record);
}