package cn.com.user.mapper;

import cn.com.user.pojo.TExaPaperInfo;
import cn.com.user.pojo.TExaPaperInfoExample;
import cn.com.user.pojo.exam.QuestionInfoVO;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TExaPaperInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TExaPaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TExaPaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByPrimaryKey(String examinationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TExaPaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TExaPaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TExaPaperInfo> selectByExample(TExaPaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    TExaPaperInfo selectByPrimaryKey(String examinationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TExaPaperInfo record, @Param("example") TExaPaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TExaPaperInfo record, @Param("example") TExaPaperInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKeySelective(TExaPaperInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKey(TExaPaperInfo record);

	List<QuestionInfoVO> findQuestions(Map<String, Object> questionmap);

	void insertExaminationInfo(Map<String, Object> questionmap);
}