package cn.com.user.mapper;

import cn.com.user.pojo.TExaPaper;
import cn.com.user.pojo.TExaPaperExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TExaPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TExaPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TExaPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByPrimaryKey(String examinationNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TExaPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TExaPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TExaPaper> selectByExample(TExaPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    TExaPaper selectByPrimaryKey(String examinationNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TExaPaper record, @Param("example") TExaPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TExaPaper record, @Param("example") TExaPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKeySelective(TExaPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_PAPER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKey(TExaPaper record);

	List<TExaPaper> findAll();

	void insertByType(Map<String, Object> map);

	List<TExaPaper> findBySubject(Map<String, String> papermap);

}