package cn.com.user.mapper;

import cn.com.user.pojo.TExaQuestions;
import cn.com.user.pojo.TExaQuestionsExample;
import cn.com.user.pojo.exam.QuestionBankVO;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TExaQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TExaQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TExaQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByPrimaryKey(String questionsNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TExaQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TExaQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TExaQuestions> selectByExample(TExaQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    TExaQuestions selectByPrimaryKey(String questionsNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TExaQuestions record, @Param("example") TExaQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TExaQuestions record, @Param("example") TExaQuestionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKeySelective(TExaQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTIONS
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKey(TExaQuestions record);

	void deleteBySubjectno(BigDecimal subjectNo);

	List<QuestionBankVO> findBySeacher(Map<String, String> map);

	void insertList(List<TExaQuestions> list);
}