package cn.com.user.mapper;

import cn.com.user.pojo.TExaminationInfo;
import cn.com.user.pojo.TExaminationInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TExaminationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TExaminationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TExaminationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByPrimaryKey(String examinationInfoNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TExaminationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TExaminationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TExaminationInfo> selectByExample(TExaminationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    TExaminationInfo selectByPrimaryKey(String examinationInfoNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TExaminationInfo record, @Param("example") TExaminationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TExaminationInfo record, @Param("example") TExaminationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKeySelective(TExaminationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKey(TExaminationInfo record);

	TExaminationInfo findOne(Map<String, String> map);
}