package cn.com.user.mapper;

import cn.com.user.pojo.TExaminationList;
import cn.com.user.pojo.TExaminationListExample;
import cn.com.user.pojo.exam.AnswerList;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TExaminationListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TExaminationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TExaminationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TExaminationList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TExaminationList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TExaminationList> selectByExample(TExaminationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    TExaminationList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TExaminationList record, @Param("example") TExaminationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TExaminationList record, @Param("example") TExaminationListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKeySelective(TExaminationList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXAMINATION_LIST
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKey(TExaminationList record);

	List<TExaminationList> findByExaminfo(Map<String, String> map);

	void updatelist(AnswerList vo);

	void updateExam(Map<String, Object> map);
}