package cn.com.user.mapper;

import cn.com.user.pojo.TLesSubRelation;
import cn.com.user.pojo.TLesSubRelationExample;

import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLesSubRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LES_SUB_RELATION
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TLesSubRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LES_SUB_RELATION
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TLesSubRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LES_SUB_RELATION
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TLesSubRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LES_SUB_RELATION
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TLesSubRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LES_SUB_RELATION
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TLesSubRelation> selectByExample(TLesSubRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LES_SUB_RELATION
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TLesSubRelation record, @Param("example") TLesSubRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_LES_SUB_RELATION
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TLesSubRelation record, @Param("example") TLesSubRelationExample example);

	void deleteByLessonid(String lessonid);

	void insertList(List<TLesSubRelation> list);

	void deleteBySubjectno(BigDecimal subject);
}