package cn.com.user.mapper;

import cn.com.user.pojo.TSubjectInfo;
import cn.com.user.pojo.TSubjectInfoExample;
import cn.com.user.pojo.information.MenuVO;
import cn.com.user.pojo.information.ProductAndSubject;
import cn.com.user.pojo.information.SubjectVO;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TSubjectInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TSubjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TSubjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal subjectNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TSubjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TSubjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TSubjectInfo> selectByExample(TSubjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    TSubjectInfo selectByPrimaryKey(BigDecimal subjectNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSubjectInfo record, @Param("example") TSubjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TSubjectInfo record, @Param("example") TSubjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKeySelective(TSubjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKey(TSubjectInfo record);

	List<ProductAndSubject> productAndSubject(String lessonid);

	List<SubjectVO> findBySearche();

	List<MenuVO> findMenu(Map<String, String> map);

	int findMaxno(Map<String, Object> map);
}