package cn.com.user.mapper;

import cn.com.user.pojo.TUserStudent;
import cn.com.user.pojo.TUserStudentExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TUserStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int countByExample(TUserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByExample(TUserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int deleteByPrimaryKey(String studentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insert(TUserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int insertSelective(TUserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    List<TUserStudent> selectByExample(TUserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    TUserStudent selectByPrimaryKey(String studentNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TUserStudent record, @Param("example") TUserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByExample(@Param("record") TUserStudent record, @Param("example") TUserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKeySelective(TUserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_STUDENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    int updateByPrimaryKey(TUserStudent record);
    int check(String studentNo);

	List<TUserStudent> findBySearch(Map<String, String> map);
}