package cn.com.user.pojo;

public class PUmAuthorityResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_AUTHORITY_RESOURCE.AUTHORITYID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private String authorityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_AUTHORITY_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_AUTHORITY_RESOURCE.FLAGINFO
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private String flaginfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_AUTHORITY_RESOURCE.AUTHORITYID
     *
     * @return the value of P_UM_AUTHORITY_RESOURCE.AUTHORITYID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public String getAuthorityid() {
        return authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_AUTHORITY_RESOURCE.AUTHORITYID
     *
     * @param authorityid the value for P_UM_AUTHORITY_RESOURCE.AUTHORITYID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setAuthorityid(String authorityid) {
        this.authorityid = authorityid == null ? null : authorityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_AUTHORITY_RESOURCE.RESOURCE_ID
     *
     * @return the value of P_UM_AUTHORITY_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_AUTHORITY_RESOURCE.RESOURCE_ID
     *
     * @param resourceId the value for P_UM_AUTHORITY_RESOURCE.RESOURCE_ID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_AUTHORITY_RESOURCE.FLAGINFO
     *
     * @return the value of P_UM_AUTHORITY_RESOURCE.FLAGINFO
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public String getFlaginfo() {
        return flaginfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_AUTHORITY_RESOURCE.FLAGINFO
     *
     * @param flaginfo the value for P_UM_AUTHORITY_RESOURCE.FLAGINFO
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setFlaginfo(String flaginfo) {
        this.flaginfo = flaginfo == null ? null : flaginfo.trim();
    }

	public PUmAuthorityResource(String authorityid, String resourceId, String flaginfo) {
		super();
		this.authorityid = authorityid;
		this.resourceId = resourceId;
		this.flaginfo = flaginfo;
	}

	public PUmAuthorityResource() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}