package cn.com.user.pojo;

import java.math.BigDecimal;

public class PUmRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_ROLE.ROLEID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_ROLE.ROLENAME
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_ROLE.DESCN
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private String descn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_ROLE.CODE
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_ROLE.FLAGINFO
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private String flaginfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_ROLE.SORT
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    private BigDecimal sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_ROLE.ROLEID
     *
     * @return the value of P_UM_ROLE.ROLEID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_ROLE.ROLEID
     *
     * @param roleid the value for P_UM_ROLE.ROLEID
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_ROLE.ROLENAME
     *
     * @return the value of P_UM_ROLE.ROLENAME
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_ROLE.ROLENAME
     *
     * @param rolename the value for P_UM_ROLE.ROLENAME
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_ROLE.DESCN
     *
     * @return the value of P_UM_ROLE.DESCN
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_ROLE.DESCN
     *
     * @param descn the value for P_UM_ROLE.DESCN
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_ROLE.CODE
     *
     * @return the value of P_UM_ROLE.CODE
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_ROLE.CODE
     *
     * @param code the value for P_UM_ROLE.CODE
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_ROLE.FLAGINFO
     *
     * @return the value of P_UM_ROLE.FLAGINFO
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public String getFlaginfo() {
        return flaginfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_ROLE.FLAGINFO
     *
     * @param flaginfo the value for P_UM_ROLE.FLAGINFO
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setFlaginfo(String flaginfo) {
        this.flaginfo = flaginfo == null ? null : flaginfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_ROLE.SORT
     *
     * @return the value of P_UM_ROLE.SORT
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public BigDecimal getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_ROLE.SORT
     *
     * @param sort the value for P_UM_ROLE.SORT
     *
     * @mbggenerated Fri Aug 04 17:04:42 CST 2017
     */
    public void setSort(BigDecimal sort) {
        this.sort = sort;
    }

	public PUmRole(String roleid, String rolename, String descn, String code, String flaginfo, BigDecimal sort) {
		super();
		this.roleid = roleid;
		this.rolename = rolename;
		this.descn = descn;
		this.code = code;
		this.flaginfo = flaginfo;
		this.sort = sort;
	}

	public PUmRole() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}