package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class PUmResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.RESOURCE_ID
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private String resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.RESOURCE_NAME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.RESOURCE_TYPE
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.PRIORITY
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private BigDecimal priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.RESOURCE_URL
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private String resourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.RESOURCE_DEC
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private String resourceDec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.ENABLED
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private BigDecimal enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.CREATE_TIME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_UM_RESOURCES.UPDATE_TIME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.RESOURCE_ID
     *
     * @return the value of P_UM_RESOURCES.RESOURCE_ID
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.RESOURCE_ID
     *
     * @param resourceId the value for P_UM_RESOURCES.RESOURCE_ID
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.RESOURCE_NAME
     *
     * @return the value of P_UM_RESOURCES.RESOURCE_NAME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.RESOURCE_NAME
     *
     * @param resourceName the value for P_UM_RESOURCES.RESOURCE_NAME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.RESOURCE_TYPE
     *
     * @return the value of P_UM_RESOURCES.RESOURCE_TYPE
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.RESOURCE_TYPE
     *
     * @param resourceType the value for P_UM_RESOURCES.RESOURCE_TYPE
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.PRIORITY
     *
     * @return the value of P_UM_RESOURCES.PRIORITY
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public BigDecimal getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.PRIORITY
     *
     * @param priority the value for P_UM_RESOURCES.PRIORITY
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.RESOURCE_URL
     *
     * @return the value of P_UM_RESOURCES.RESOURCE_URL
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public String getResourceUrl() {
        return resourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.RESOURCE_URL
     *
     * @param resourceUrl the value for P_UM_RESOURCES.RESOURCE_URL
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setResourceUrl(String resourceUrl) {
        this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.RESOURCE_DEC
     *
     * @return the value of P_UM_RESOURCES.RESOURCE_DEC
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public String getResourceDec() {
        return resourceDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.RESOURCE_DEC
     *
     * @param resourceDec the value for P_UM_RESOURCES.RESOURCE_DEC
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setResourceDec(String resourceDec) {
        this.resourceDec = resourceDec == null ? null : resourceDec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.ENABLED
     *
     * @return the value of P_UM_RESOURCES.ENABLED
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public BigDecimal getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.ENABLED
     *
     * @param enabled the value for P_UM_RESOURCES.ENABLED
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setEnabled(BigDecimal enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.CREATE_TIME
     *
     * @return the value of P_UM_RESOURCES.CREATE_TIME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.CREATE_TIME
     *
     * @param createTime the value for P_UM_RESOURCES.CREATE_TIME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_UM_RESOURCES.UPDATE_TIME
     *
     * @return the value of P_UM_RESOURCES.UPDATE_TIME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_UM_RESOURCES.UPDATE_TIME
     *
     * @param updateTime the value for P_UM_RESOURCES.UPDATE_TIME
     *
     * @mbggenerated Fri Aug 04 17:12:29 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public PUmResources(String resourceId, String resourceName, String resourceType, BigDecimal priority,
			String resourceUrl, String resourceDec, BigDecimal enabled, Date createTime, Date updateTime) {
		super();
		this.resourceId = resourceId;
		this.resourceName = resourceName;
		this.resourceType = resourceType;
		this.priority = priority;
		this.resourceUrl = resourceUrl;
		this.resourceDec = resourceDec;
		this.enabled = enabled;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public PUmResources() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}