package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TExaPaperList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.EXAMINATI_LIST_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinatiListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.EXAMINATION_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.QUESTION_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal questionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.ANSWER_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal answerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.ANSWER_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String answerContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.ISTRUE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal istrue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.CREATE_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_LIST.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.EXAMINATI_LIST_ID
     *
     * @return the value of T_EXA_PAPER_LIST.EXAMINATI_LIST_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminatiListId() {
        return examinatiListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.EXAMINATI_LIST_ID
     *
     * @param examinatiListId the value for T_EXA_PAPER_LIST.EXAMINATI_LIST_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminatiListId(String examinatiListId) {
        this.examinatiListId = examinatiListId == null ? null : examinatiListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.EXAMINATION_ID
     *
     * @return the value of T_EXA_PAPER_LIST.EXAMINATION_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminationId() {
        return examinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.EXAMINATION_ID
     *
     * @param examinationId the value for T_EXA_PAPER_LIST.EXAMINATION_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationId(String examinationId) {
        this.examinationId = examinationId == null ? null : examinationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.QUESTION_NUM
     *
     * @return the value of T_EXA_PAPER_LIST.QUESTION_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getQuestionNum() {
        return questionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.QUESTION_NUM
     *
     * @param questionNum the value for T_EXA_PAPER_LIST.QUESTION_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setQuestionNum(BigDecimal questionNum) {
        this.questionNum = questionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.ANSWER_NUM
     *
     * @return the value of T_EXA_PAPER_LIST.ANSWER_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getAnswerNum() {
        return answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.ANSWER_NUM
     *
     * @param answerNum the value for T_EXA_PAPER_LIST.ANSWER_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setAnswerNum(BigDecimal answerNum) {
        this.answerNum = answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.ANSWER_CONTENT
     *
     * @return the value of T_EXA_PAPER_LIST.ANSWER_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.ANSWER_CONTENT
     *
     * @param answerContent the value for T_EXA_PAPER_LIST.ANSWER_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent == null ? null : answerContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.ISTRUE
     *
     * @return the value of T_EXA_PAPER_LIST.ISTRUE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getIstrue() {
        return istrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.ISTRUE
     *
     * @param istrue the value for T_EXA_PAPER_LIST.ISTRUE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setIstrue(BigDecimal istrue) {
        this.istrue = istrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.CREATE_USER
     *
     * @return the value of T_EXA_PAPER_LIST.CREATE_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.CREATE_USER
     *
     * @param createUser the value for T_EXA_PAPER_LIST.CREATE_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.CREATE_TIME
     *
     * @return the value of T_EXA_PAPER_LIST.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.CREATE_TIME
     *
     * @param createTime the value for T_EXA_PAPER_LIST.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_LIST.UPDATE_TIME
     *
     * @return the value of T_EXA_PAPER_LIST.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_LIST.UPDATE_TIME
     *
     * @param updateTime the value for T_EXA_PAPER_LIST.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}