package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TExaAnswerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_ANSWER_INFO.ANSWER_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String answerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_ANSWER_INFO.QUESTION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String questionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_ANSWER_INFO.ANSWER_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal answerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_ANSWER_INFO.ANSWER_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String answerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_ANSWER_INFO.ISTRUE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal istrue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_ANSWER_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_ANSWER_INFO.UPPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date uppdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_ANSWER_INFO.ANSWER_ID
     *
     * @return the value of T_EXA_ANSWER_INFO.ANSWER_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_ANSWER_INFO.ANSWER_ID
     *
     * @param answerId the value for T_EXA_ANSWER_INFO.ANSWER_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setAnswerId(String answerId) {
        this.answerId = answerId == null ? null : answerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_ANSWER_INFO.QUESTION_NO
     *
     * @return the value of T_EXA_ANSWER_INFO.QUESTION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getQuestionNo() {
        return questionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_ANSWER_INFO.QUESTION_NO
     *
     * @param questionNo the value for T_EXA_ANSWER_INFO.QUESTION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setQuestionNo(String questionNo) {
        this.questionNo = questionNo == null ? null : questionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_ANSWER_INFO.ANSWER_NUM
     *
     * @return the value of T_EXA_ANSWER_INFO.ANSWER_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getAnswerNum() {
        return answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_ANSWER_INFO.ANSWER_NUM
     *
     * @param answerNum the value for T_EXA_ANSWER_INFO.ANSWER_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setAnswerNum(BigDecimal answerNum) {
        this.answerNum = answerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_ANSWER_INFO.ANSWER_NAME
     *
     * @return the value of T_EXA_ANSWER_INFO.ANSWER_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getAnswerName() {
        return answerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_ANSWER_INFO.ANSWER_NAME
     *
     * @param answerName the value for T_EXA_ANSWER_INFO.ANSWER_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setAnswerName(String answerName) {
        this.answerName = answerName == null ? null : answerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_ANSWER_INFO.ISTRUE
     *
     * @return the value of T_EXA_ANSWER_INFO.ISTRUE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getIstrue() {
        return istrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_ANSWER_INFO.ISTRUE
     *
     * @param istrue the value for T_EXA_ANSWER_INFO.ISTRUE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setIstrue(BigDecimal istrue) {
        this.istrue = istrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_ANSWER_INFO.CREATE_TIME
     *
     * @return the value of T_EXA_ANSWER_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_ANSWER_INFO.CREATE_TIME
     *
     * @param createTime the value for T_EXA_ANSWER_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_ANSWER_INFO.UPPDATE_TIME
     *
     * @return the value of T_EXA_ANSWER_INFO.UPPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getUppdateTime() {
        return uppdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_ANSWER_INFO.UPPDATE_TIME
     *
     * @param uppdateTime the value for T_EXA_ANSWER_INFO.UPPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setUppdateTime(Date uppdateTime) {
        this.uppdateTime = uppdateTime;
    }
}