package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TExaPaperScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_SCORE.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_SCORE.QUESTION_TYPE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal questionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_SCORE.QUESTION_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal questionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_SCORE.QUESTION_SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal questionScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_SCORE.TOTAL_SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_SCORE.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER_SCORE.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_SCORE.EXAMINATION_NO
     *
     * @return the value of T_EXA_PAPER_SCORE.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminationNo() {
        return examinationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_SCORE.EXAMINATION_NO
     *
     * @param examinationNo the value for T_EXA_PAPER_SCORE.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationNo(String examinationNo) {
        this.examinationNo = examinationNo == null ? null : examinationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_SCORE.QUESTION_TYPE
     *
     * @return the value of T_EXA_PAPER_SCORE.QUESTION_TYPE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_SCORE.QUESTION_TYPE
     *
     * @param questionType the value for T_EXA_PAPER_SCORE.QUESTION_TYPE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setQuestionType(BigDecimal questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_SCORE.QUESTION_NUM
     *
     * @return the value of T_EXA_PAPER_SCORE.QUESTION_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getQuestionNum() {
        return questionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_SCORE.QUESTION_NUM
     *
     * @param questionNum the value for T_EXA_PAPER_SCORE.QUESTION_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setQuestionNum(BigDecimal questionNum) {
        this.questionNum = questionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_SCORE.QUESTION_SCORE
     *
     * @return the value of T_EXA_PAPER_SCORE.QUESTION_SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getQuestionScore() {
        return questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_SCORE.QUESTION_SCORE
     *
     * @param questionScore the value for T_EXA_PAPER_SCORE.QUESTION_SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setQuestionScore(BigDecimal questionScore) {
        this.questionScore = questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_SCORE.TOTAL_SCORE
     *
     * @return the value of T_EXA_PAPER_SCORE.TOTAL_SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_SCORE.TOTAL_SCORE
     *
     * @param totalScore the value for T_EXA_PAPER_SCORE.TOTAL_SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setTotalScore(BigDecimal totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_SCORE.CREATE_TIME
     *
     * @return the value of T_EXA_PAPER_SCORE.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_SCORE.CREATE_TIME
     *
     * @param createTime the value for T_EXA_PAPER_SCORE.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER_SCORE.UPDATE_TIME
     *
     * @return the value of T_EXA_PAPER_SCORE.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER_SCORE.UPDATE_TIME
     *
     * @param updateTime the value for T_EXA_PAPER_SCORE.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}