package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TExaPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.EXAMINATION_TYPE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal examinationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.EXAMINATION_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.EXAMINATION_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinationContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.SUBJECT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal subjectNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.EXAM_LENGTH
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal examLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.STATE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.CREATE_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXA_PAPER.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.EXAMINATION_NO
     *
     * @return the value of T_EXA_PAPER.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminationNo() {
        return examinationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.EXAMINATION_NO
     *
     * @param examinationNo the value for T_EXA_PAPER.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationNo(String examinationNo) {
        this.examinationNo = examinationNo == null ? null : examinationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.EXAMINATION_TYPE
     *
     * @return the value of T_EXA_PAPER.EXAMINATION_TYPE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getExaminationType() {
        return examinationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.EXAMINATION_TYPE
     *
     * @param examinationType the value for T_EXA_PAPER.EXAMINATION_TYPE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationType(BigDecimal examinationType) {
        this.examinationType = examinationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.EXAMINATION_NAME
     *
     * @return the value of T_EXA_PAPER.EXAMINATION_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminationName() {
        return examinationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.EXAMINATION_NAME
     *
     * @param examinationName the value for T_EXA_PAPER.EXAMINATION_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationName(String examinationName) {
        this.examinationName = examinationName == null ? null : examinationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.EXAMINATION_CONTENT
     *
     * @return the value of T_EXA_PAPER.EXAMINATION_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminationContent() {
        return examinationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.EXAMINATION_CONTENT
     *
     * @param examinationContent the value for T_EXA_PAPER.EXAMINATION_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationContent(String examinationContent) {
        this.examinationContent = examinationContent == null ? null : examinationContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.SUBJECT_NO
     *
     * @return the value of T_EXA_PAPER.SUBJECT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getSubjectNo() {
        return subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.SUBJECT_NO
     *
     * @param subjectNo the value for T_EXA_PAPER.SUBJECT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setSubjectNo(BigDecimal subjectNo) {
        this.subjectNo = subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.EXAM_LENGTH
     *
     * @return the value of T_EXA_PAPER.EXAM_LENGTH
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getExamLength() {
        return examLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.EXAM_LENGTH
     *
     * @param examLength the value for T_EXA_PAPER.EXAM_LENGTH
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExamLength(BigDecimal examLength) {
        this.examLength = examLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.STATE
     *
     * @return the value of T_EXA_PAPER.STATE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.STATE
     *
     * @param state the value for T_EXA_PAPER.STATE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.CREATE_USER
     *
     * @return the value of T_EXA_PAPER.CREATE_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.CREATE_USER
     *
     * @param createUser the value for T_EXA_PAPER.CREATE_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.CREATE_TIME
     *
     * @return the value of T_EXA_PAPER.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.CREATE_TIME
     *
     * @param createTime the value for T_EXA_PAPER.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXA_PAPER.UPDATE_TIME
     *
     * @return the value of T_EXA_PAPER.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXA_PAPER.UPDATE_TIME
     *
     * @param updateTime the value for T_EXA_PAPER.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    private TExaPaperScore paperscore;
    
	public TExaPaperScore getPaperscore() {
		return paperscore;
	}

	public void setPaperscore(TExaPaperScore paperscore) {
		this.paperscore = paperscore;
	}

	public TExaPaper(String examinationNo, BigDecimal examinationType, String examinationName,
			String examinationContent, BigDecimal subjectNo, BigDecimal examLength, BigDecimal state, String createUser,
			Date createTime, Date updateTime, TExaPaperScore paperscore) {
		super();
		this.examinationNo = examinationNo;
		this.examinationType = examinationType;
		this.examinationName = examinationName;
		this.examinationContent = examinationContent;
		this.subjectNo = subjectNo;
		this.examLength = examLength;
		this.state = state;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.paperscore = paperscore;
	}

	public TExaPaper() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}