package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TExaminationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.EXAMINATION_INFO_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinationInfoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinationNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.EXAMINATION_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String examinationUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.RIGHT_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal rightNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.ERROR_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal errorNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.EXAMINATION_LENGTH
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal examinationLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.START_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EXAMINATION_INFO.END_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.EXAMINATION_INFO_NO
     *
     * @return the value of T_EXAMINATION_INFO.EXAMINATION_INFO_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminationInfoNo() {
        return examinationInfoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.EXAMINATION_INFO_NO
     *
     * @param examinationInfoNo the value for T_EXAMINATION_INFO.EXAMINATION_INFO_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationInfoNo(String examinationInfoNo) {
        this.examinationInfoNo = examinationInfoNo == null ? null : examinationInfoNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.EXAMINATION_NO
     *
     * @return the value of T_EXAMINATION_INFO.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminationNo() {
        return examinationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.EXAMINATION_NO
     *
     * @param examinationNo the value for T_EXAMINATION_INFO.EXAMINATION_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationNo(String examinationNo) {
        this.examinationNo = examinationNo == null ? null : examinationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.EXAMINATION_USER
     *
     * @return the value of T_EXAMINATION_INFO.EXAMINATION_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getExaminationUser() {
        return examinationUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.EXAMINATION_USER
     *
     * @param examinationUser the value for T_EXAMINATION_INFO.EXAMINATION_USER
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationUser(String examinationUser) {
        this.examinationUser = examinationUser == null ? null : examinationUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.RIGHT_NUM
     *
     * @return the value of T_EXAMINATION_INFO.RIGHT_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getRightNum() {
        return rightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.RIGHT_NUM
     *
     * @param rightNum the value for T_EXAMINATION_INFO.RIGHT_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setRightNum(BigDecimal rightNum) {
        this.rightNum = rightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.ERROR_NUM
     *
     * @return the value of T_EXAMINATION_INFO.ERROR_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getErrorNum() {
        return errorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.ERROR_NUM
     *
     * @param errorNum the value for T_EXAMINATION_INFO.ERROR_NUM
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setErrorNum(BigDecimal errorNum) {
        this.errorNum = errorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.SCORE
     *
     * @return the value of T_EXAMINATION_INFO.SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.SCORE
     *
     * @param score the value for T_EXAMINATION_INFO.SCORE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.EXAMINATION_LENGTH
     *
     * @return the value of T_EXAMINATION_INFO.EXAMINATION_LENGTH
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getExaminationLength() {
        return examinationLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.EXAMINATION_LENGTH
     *
     * @param examinationLength the value for T_EXAMINATION_INFO.EXAMINATION_LENGTH
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setExaminationLength(BigDecimal examinationLength) {
        this.examinationLength = examinationLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.START_TIME
     *
     * @return the value of T_EXAMINATION_INFO.START_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.START_TIME
     *
     * @param startTime the value for T_EXAMINATION_INFO.START_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EXAMINATION_INFO.END_TIME
     *
     * @return the value of T_EXAMINATION_INFO.END_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EXAMINATION_INFO.END_TIME
     *
     * @param endTime the value for T_EXAMINATION_INFO.END_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

	public TExaminationInfo(String examinationInfoNo, String examinationNo, String examinationUser, BigDecimal rightNum,
			BigDecimal errorNum, BigDecimal score, BigDecimal examinationLength, Date startTime, Date endTime) {
		super();
		this.examinationInfoNo = examinationInfoNo;
		this.examinationNo = examinationNo;
		this.examinationUser = examinationUser;
		this.rightNum = rightNum;
		this.errorNum = errorNum;
		this.score = score;
		this.examinationLength = examinationLength;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public TExaminationInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}