package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TExaQuestionDetailedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public TExaQuestionDetailedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestionNoIsNull() {
            addCriterion("QUESTION_NO is null");
            return (Criteria) this;
        }

        public Criteria andQuestionNoIsNotNull() {
            addCriterion("QUESTION_NO is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionNoEqualTo(String value) {
            addCriterion("QUESTION_NO =", value, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoNotEqualTo(String value) {
            addCriterion("QUESTION_NO <>", value, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoGreaterThan(String value) {
            addCriterion("QUESTION_NO >", value, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION_NO >=", value, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoLessThan(String value) {
            addCriterion("QUESTION_NO <", value, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoLessThanOrEqualTo(String value) {
            addCriterion("QUESTION_NO <=", value, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoLike(String value) {
            addCriterion("QUESTION_NO like", value, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoNotLike(String value) {
            addCriterion("QUESTION_NO not like", value, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoIn(List<String> values) {
            addCriterion("QUESTION_NO in", values, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoNotIn(List<String> values) {
            addCriterion("QUESTION_NO not in", values, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoBetween(String value1, String value2) {
            addCriterion("QUESTION_NO between", value1, value2, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNoNotBetween(String value1, String value2) {
            addCriterion("QUESTION_NO not between", value1, value2, "questionNo");
            return (Criteria) this;
        }

        public Criteria andQuestionNumIsNull() {
            addCriterion("QUESTION_NUM is null");
            return (Criteria) this;
        }

        public Criteria andQuestionNumIsNotNull() {
            addCriterion("QUESTION_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionNumEqualTo(BigDecimal value) {
            addCriterion("QUESTION_NUM =", value, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumNotEqualTo(BigDecimal value) {
            addCriterion("QUESTION_NUM <>", value, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumGreaterThan(BigDecimal value) {
            addCriterion("QUESTION_NUM >", value, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("QUESTION_NUM >=", value, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumLessThan(BigDecimal value) {
            addCriterion("QUESTION_NUM <", value, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("QUESTION_NUM <=", value, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumIn(List<BigDecimal> values) {
            addCriterion("QUESTION_NUM in", values, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumNotIn(List<BigDecimal> values) {
            addCriterion("QUESTION_NUM not in", values, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUESTION_NUM between", value1, value2, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUESTION_NUM not between", value1, value2, "questionNum");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeIsNull() {
            addCriterion("QUESTION_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeIsNotNull() {
            addCriterion("QUESTION_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeEqualTo(BigDecimal value) {
            addCriterion("QUESTION_TYPE =", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeNotEqualTo(BigDecimal value) {
            addCriterion("QUESTION_TYPE <>", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeGreaterThan(BigDecimal value) {
            addCriterion("QUESTION_TYPE >", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("QUESTION_TYPE >=", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeLessThan(BigDecimal value) {
            addCriterion("QUESTION_TYPE <", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("QUESTION_TYPE <=", value, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeIn(List<BigDecimal> values) {
            addCriterion("QUESTION_TYPE in", values, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeNotIn(List<BigDecimal> values) {
            addCriterion("QUESTION_TYPE not in", values, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUESTION_TYPE between", value1, value2, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionTypeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QUESTION_TYPE not between", value1, value2, "questionType");
            return (Criteria) this;
        }

        public Criteria andQuestionNameIsNull() {
            addCriterion("QUESTION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andQuestionNameIsNotNull() {
            addCriterion("QUESTION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionNameEqualTo(String value) {
            addCriterion("QUESTION_NAME =", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameNotEqualTo(String value) {
            addCriterion("QUESTION_NAME <>", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameGreaterThan(String value) {
            addCriterion("QUESTION_NAME >", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION_NAME >=", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameLessThan(String value) {
            addCriterion("QUESTION_NAME <", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameLessThanOrEqualTo(String value) {
            addCriterion("QUESTION_NAME <=", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameLike(String value) {
            addCriterion("QUESTION_NAME like", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameNotLike(String value) {
            addCriterion("QUESTION_NAME not like", value, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameIn(List<String> values) {
            addCriterion("QUESTION_NAME in", values, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameNotIn(List<String> values) {
            addCriterion("QUESTION_NAME not in", values, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameBetween(String value1, String value2) {
            addCriterion("QUESTION_NAME between", value1, value2, "questionName");
            return (Criteria) this;
        }

        public Criteria andQuestionNameNotBetween(String value1, String value2) {
            addCriterion("QUESTION_NAME not between", value1, value2, "questionName");
            return (Criteria) this;
        }

        public Criteria andRightKeyIsNull() {
            addCriterion("RIGHT_KEY is null");
            return (Criteria) this;
        }

        public Criteria andRightKeyIsNotNull() {
            addCriterion("RIGHT_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andRightKeyEqualTo(String value) {
            addCriterion("RIGHT_KEY =", value, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyNotEqualTo(String value) {
            addCriterion("RIGHT_KEY <>", value, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyGreaterThan(String value) {
            addCriterion("RIGHT_KEY >", value, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyGreaterThanOrEqualTo(String value) {
            addCriterion("RIGHT_KEY >=", value, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyLessThan(String value) {
            addCriterion("RIGHT_KEY <", value, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyLessThanOrEqualTo(String value) {
            addCriterion("RIGHT_KEY <=", value, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyLike(String value) {
            addCriterion("RIGHT_KEY like", value, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyNotLike(String value) {
            addCriterion("RIGHT_KEY not like", value, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyIn(List<String> values) {
            addCriterion("RIGHT_KEY in", values, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyNotIn(List<String> values) {
            addCriterion("RIGHT_KEY not in", values, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyBetween(String value1, String value2) {
            addCriterion("RIGHT_KEY between", value1, value2, "rightKey");
            return (Criteria) this;
        }

        public Criteria andRightKeyNotBetween(String value1, String value2) {
            addCriterion("RIGHT_KEY not between", value1, value2, "rightKey");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoIsNull() {
            addCriterion("QUESTIONS_NO is null");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoIsNotNull() {
            addCriterion("QUESTIONS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoEqualTo(String value) {
            addCriterion("QUESTIONS_NO =", value, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoNotEqualTo(String value) {
            addCriterion("QUESTIONS_NO <>", value, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoGreaterThan(String value) {
            addCriterion("QUESTIONS_NO >", value, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTIONS_NO >=", value, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoLessThan(String value) {
            addCriterion("QUESTIONS_NO <", value, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoLessThanOrEqualTo(String value) {
            addCriterion("QUESTIONS_NO <=", value, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoLike(String value) {
            addCriterion("QUESTIONS_NO like", value, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoNotLike(String value) {
            addCriterion("QUESTIONS_NO not like", value, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoIn(List<String> values) {
            addCriterion("QUESTIONS_NO in", values, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoNotIn(List<String> values) {
            addCriterion("QUESTIONS_NO not in", values, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoBetween(String value1, String value2) {
            addCriterion("QUESTIONS_NO between", value1, value2, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andQuestionsNoNotBetween(String value1, String value2) {
            addCriterion("QUESTIONS_NO not between", value1, value2, "questionsNo");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(BigDecimal value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(BigDecimal value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(BigDecimal value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(BigDecimal value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<BigDecimal> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<BigDecimal> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 14 15:21:26 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_EXA_QUESTION_DETAILED
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}