package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TLessonProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LESSON_PRODUCT_INFO.LESSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String lessonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LESSON_PRODUCT_INFO.LESSON_CODE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String lessonCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LESSON_PRODUCT_INFO.LESSON_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String lessonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LESSON_PRODUCT_INFO.LESSON_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String lessonContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LESSON_PRODUCT_INFO.LESSON_CYCLE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private BigDecimal lessonCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LESSON_PRODUCT_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_LESSON_PRODUCT_INFO.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LESSON_PRODUCT_INFO.LESSON_ID
     *
     * @return the value of T_LESSON_PRODUCT_INFO.LESSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LESSON_PRODUCT_INFO.LESSON_ID
     *
     * @param lessonId the value for T_LESSON_PRODUCT_INFO.LESSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setLessonId(String lessonId) {
        this.lessonId = lessonId == null ? null : lessonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LESSON_PRODUCT_INFO.LESSON_CODE
     *
     * @return the value of T_LESSON_PRODUCT_INFO.LESSON_CODE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getLessonCode() {
        return lessonCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LESSON_PRODUCT_INFO.LESSON_CODE
     *
     * @param lessonCode the value for T_LESSON_PRODUCT_INFO.LESSON_CODE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setLessonCode(String lessonCode) {
        this.lessonCode = lessonCode == null ? null : lessonCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LESSON_PRODUCT_INFO.LESSON_NAME
     *
     * @return the value of T_LESSON_PRODUCT_INFO.LESSON_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getLessonName() {
        return lessonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LESSON_PRODUCT_INFO.LESSON_NAME
     *
     * @param lessonName the value for T_LESSON_PRODUCT_INFO.LESSON_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setLessonName(String lessonName) {
        this.lessonName = lessonName == null ? null : lessonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LESSON_PRODUCT_INFO.LESSON_CONTENT
     *
     * @return the value of T_LESSON_PRODUCT_INFO.LESSON_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getLessonContent() {
        return lessonContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LESSON_PRODUCT_INFO.LESSON_CONTENT
     *
     * @param lessonContent the value for T_LESSON_PRODUCT_INFO.LESSON_CONTENT
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setLessonContent(String lessonContent) {
        this.lessonContent = lessonContent == null ? null : lessonContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LESSON_PRODUCT_INFO.LESSON_CYCLE
     *
     * @return the value of T_LESSON_PRODUCT_INFO.LESSON_CYCLE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public BigDecimal getLessonCycle() {
        return lessonCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LESSON_PRODUCT_INFO.LESSON_CYCLE
     *
     * @param lessonCycle the value for T_LESSON_PRODUCT_INFO.LESSON_CYCLE
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setLessonCycle(BigDecimal lessonCycle) {
        this.lessonCycle = lessonCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LESSON_PRODUCT_INFO.CREATE_TIME
     *
     * @return the value of T_LESSON_PRODUCT_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LESSON_PRODUCT_INFO.CREATE_TIME
     *
     * @param createTime the value for T_LESSON_PRODUCT_INFO.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_LESSON_PRODUCT_INFO.UPDATE_TIME
     *
     * @return the value of T_LESSON_PRODUCT_INFO.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_LESSON_PRODUCT_INFO.UPDATE_TIME
     *
     * @param updateTime the value for T_LESSON_PRODUCT_INFO.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	public TLessonProductInfo(String lessonId, String lessonCode, String lessonName, String lessonContent,
			BigDecimal lessonCycle, Date createTime, Date updateTime) {
		super();
		this.lessonId = lessonId;
		this.lessonCode = lessonCode;
		this.lessonName = lessonName;
		this.lessonContent = lessonContent;
		this.lessonCycle = lessonCycle;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public TLessonProductInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}