package cn.com.user.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSubjectInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public TSubjectInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubjectNoIsNull() {
            addCriterion("SUBJECT_NO is null");
            return (Criteria) this;
        }

        public Criteria andSubjectNoIsNotNull() {
            addCriterion("SUBJECT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectNoEqualTo(BigDecimal value) {
            addCriterion("SUBJECT_NO =", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoNotEqualTo(BigDecimal value) {
            addCriterion("SUBJECT_NO <>", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoGreaterThan(BigDecimal value) {
            addCriterion("SUBJECT_NO >", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUBJECT_NO >=", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoLessThan(BigDecimal value) {
            addCriterion("SUBJECT_NO <", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUBJECT_NO <=", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoIn(List<BigDecimal> values) {
            addCriterion("SUBJECT_NO in", values, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoNotIn(List<BigDecimal> values) {
            addCriterion("SUBJECT_NO not in", values, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUBJECT_NO between", value1, value2, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUBJECT_NO not between", value1, value2, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeIsNull() {
            addCriterion("SUBJECT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeIsNotNull() {
            addCriterion("SUBJECT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeEqualTo(String value) {
            addCriterion("SUBJECT_CODE =", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeNotEqualTo(String value) {
            addCriterion("SUBJECT_CODE <>", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeGreaterThan(String value) {
            addCriterion("SUBJECT_CODE >", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT_CODE >=", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeLessThan(String value) {
            addCriterion("SUBJECT_CODE <", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT_CODE <=", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeLike(String value) {
            addCriterion("SUBJECT_CODE like", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeNotLike(String value) {
            addCriterion("SUBJECT_CODE not like", value, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeIn(List<String> values) {
            addCriterion("SUBJECT_CODE in", values, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeNotIn(List<String> values) {
            addCriterion("SUBJECT_CODE not in", values, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeBetween(String value1, String value2) {
            addCriterion("SUBJECT_CODE between", value1, value2, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectCodeNotBetween(String value1, String value2) {
            addCriterion("SUBJECT_CODE not between", value1, value2, "subjectCode");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNull() {
            addCriterion("SUBJECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNotNull() {
            addCriterion("SUBJECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameEqualTo(String value) {
            addCriterion("SUBJECT_NAME =", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotEqualTo(String value) {
            addCriterion("SUBJECT_NAME <>", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThan(String value) {
            addCriterion("SUBJECT_NAME >", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT_NAME >=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThan(String value) {
            addCriterion("SUBJECT_NAME <", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT_NAME <=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLike(String value) {
            addCriterion("SUBJECT_NAME like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotLike(String value) {
            addCriterion("SUBJECT_NAME not like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIn(List<String> values) {
            addCriterion("SUBJECT_NAME in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotIn(List<String> values) {
            addCriterion("SUBJECT_NAME not in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameBetween(String value1, String value2) {
            addCriterion("SUBJECT_NAME between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotBetween(String value1, String value2) {
            addCriterion("SUBJECT_NAME not between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andClassContentIsNull() {
            addCriterion("CLASS_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andClassContentIsNotNull() {
            addCriterion("CLASS_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andClassContentEqualTo(String value) {
            addCriterion("CLASS_CONTENT =", value, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentNotEqualTo(String value) {
            addCriterion("CLASS_CONTENT <>", value, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentGreaterThan(String value) {
            addCriterion("CLASS_CONTENT >", value, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentGreaterThanOrEqualTo(String value) {
            addCriterion("CLASS_CONTENT >=", value, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentLessThan(String value) {
            addCriterion("CLASS_CONTENT <", value, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentLessThanOrEqualTo(String value) {
            addCriterion("CLASS_CONTENT <=", value, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentLike(String value) {
            addCriterion("CLASS_CONTENT like", value, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentNotLike(String value) {
            addCriterion("CLASS_CONTENT not like", value, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentIn(List<String> values) {
            addCriterion("CLASS_CONTENT in", values, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentNotIn(List<String> values) {
            addCriterion("CLASS_CONTENT not in", values, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentBetween(String value1, String value2) {
            addCriterion("CLASS_CONTENT between", value1, value2, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassContentNotBetween(String value1, String value2) {
            addCriterion("CLASS_CONTENT not between", value1, value2, "classContent");
            return (Criteria) this;
        }

        public Criteria andClassTargetIsNull() {
            addCriterion("CLASS_TARGET is null");
            return (Criteria) this;
        }

        public Criteria andClassTargetIsNotNull() {
            addCriterion("CLASS_TARGET is not null");
            return (Criteria) this;
        }

        public Criteria andClassTargetEqualTo(String value) {
            addCriterion("CLASS_TARGET =", value, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetNotEqualTo(String value) {
            addCriterion("CLASS_TARGET <>", value, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetGreaterThan(String value) {
            addCriterion("CLASS_TARGET >", value, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetGreaterThanOrEqualTo(String value) {
            addCriterion("CLASS_TARGET >=", value, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetLessThan(String value) {
            addCriterion("CLASS_TARGET <", value, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetLessThanOrEqualTo(String value) {
            addCriterion("CLASS_TARGET <=", value, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetLike(String value) {
            addCriterion("CLASS_TARGET like", value, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetNotLike(String value) {
            addCriterion("CLASS_TARGET not like", value, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetIn(List<String> values) {
            addCriterion("CLASS_TARGET in", values, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetNotIn(List<String> values) {
            addCriterion("CLASS_TARGET not in", values, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetBetween(String value1, String value2) {
            addCriterion("CLASS_TARGET between", value1, value2, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassTargetNotBetween(String value1, String value2) {
            addCriterion("CLASS_TARGET not between", value1, value2, "classTarget");
            return (Criteria) this;
        }

        public Criteria andClassHourIsNull() {
            addCriterion("CLASS_HOUR is null");
            return (Criteria) this;
        }

        public Criteria andClassHourIsNotNull() {
            addCriterion("CLASS_HOUR is not null");
            return (Criteria) this;
        }

        public Criteria andClassHourEqualTo(BigDecimal value) {
            addCriterion("CLASS_HOUR =", value, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourNotEqualTo(BigDecimal value) {
            addCriterion("CLASS_HOUR <>", value, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourGreaterThan(BigDecimal value) {
            addCriterion("CLASS_HOUR >", value, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CLASS_HOUR >=", value, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourLessThan(BigDecimal value) {
            addCriterion("CLASS_HOUR <", value, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CLASS_HOUR <=", value, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourIn(List<BigDecimal> values) {
            addCriterion("CLASS_HOUR in", values, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourNotIn(List<BigDecimal> values) {
            addCriterion("CLASS_HOUR not in", values, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLASS_HOUR between", value1, value2, "classHour");
            return (Criteria) this;
        }

        public Criteria andClassHourNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLASS_HOUR not between", value1, value2, "classHour");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectIsNull() {
            addCriterion("FATHER_SUBJECT is null");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectIsNotNull() {
            addCriterion("FATHER_SUBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectEqualTo(BigDecimal value) {
            addCriterion("FATHER_SUBJECT =", value, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectNotEqualTo(BigDecimal value) {
            addCriterion("FATHER_SUBJECT <>", value, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectGreaterThan(BigDecimal value) {
            addCriterion("FATHER_SUBJECT >", value, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FATHER_SUBJECT >=", value, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectLessThan(BigDecimal value) {
            addCriterion("FATHER_SUBJECT <", value, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FATHER_SUBJECT <=", value, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectIn(List<BigDecimal> values) {
            addCriterion("FATHER_SUBJECT in", values, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectNotIn(List<BigDecimal> values) {
            addCriterion("FATHER_SUBJECT not in", values, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FATHER_SUBJECT between", value1, value2, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andFatherSubjectNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FATHER_SUBJECT not between", value1, value2, "fatherSubject");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 14 15:21:26 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_SUBJECT_INFO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}