package cn.com.user.pojo;

public class TUPRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_U_P_RELATION.USERID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_U_P_RELATION.PERSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_U_P_RELATION.TEACHER_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_U_P_RELATION.STUDENT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String studentNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_U_P_RELATION.USERID
     *
     * @return the value of T_U_P_RELATION.USERID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_U_P_RELATION.USERID
     *
     * @param userid the value for T_U_P_RELATION.USERID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_U_P_RELATION.PERSON_ID
     *
     * @return the value of T_U_P_RELATION.PERSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_U_P_RELATION.PERSON_ID
     *
     * @param personId the value for T_U_P_RELATION.PERSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_U_P_RELATION.TEACHER_ID
     *
     * @return the value of T_U_P_RELATION.TEACHER_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_U_P_RELATION.TEACHER_ID
     *
     * @param teacherId the value for T_U_P_RELATION.TEACHER_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_U_P_RELATION.STUDENT_NO
     *
     * @return the value of T_U_P_RELATION.STUDENT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_U_P_RELATION.STUDENT_NO
     *
     * @param studentNo the value for T_U_P_RELATION.STUDENT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }
}