package cn.com.user.pojo;

import java.util.Date;

public class TUserStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_STUDENT.STUDENT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String studentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_STUDENT.STUDENT_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_STUDENT.CLASS_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_STUDENT.LESSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private String lessonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_STUDENT.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_STUDENT.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_STUDENT.STUDENT_NO
     *
     * @return the value of T_USER_STUDENT.STUDENT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_STUDENT.STUDENT_NO
     *
     * @param studentNo the value for T_USER_STUDENT.STUDENT_NO
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_STUDENT.STUDENT_NAME
     *
     * @return the value of T_USER_STUDENT.STUDENT_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_STUDENT.STUDENT_NAME
     *
     * @param studentName the value for T_USER_STUDENT.STUDENT_NAME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_STUDENT.CLASS_ID
     *
     * @return the value of T_USER_STUDENT.CLASS_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_STUDENT.CLASS_ID
     *
     * @param classId the value for T_USER_STUDENT.CLASS_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_STUDENT.LESSON_ID
     *
     * @return the value of T_USER_STUDENT.LESSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public String getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_STUDENT.LESSON_ID
     *
     * @param lessonId the value for T_USER_STUDENT.LESSON_ID
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setLessonId(String lessonId) {
        this.lessonId = lessonId == null ? null : lessonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_STUDENT.CREATE_TIME
     *
     * @return the value of T_USER_STUDENT.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_STUDENT.CREATE_TIME
     *
     * @param createTime the value for T_USER_STUDENT.CREATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_STUDENT.UPDATE_TIME
     *
     * @return the value of T_USER_STUDENT.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_STUDENT.UPDATE_TIME
     *
     * @param updateTime the value for T_USER_STUDENT.UPDATE_TIME
     *
     * @mbggenerated Mon Aug 14 15:21:26 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}